// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIJRb3BkeZzRCUsTXegfm-2UdJo6QPdM',
    appId: '1:1040296536084:web:15d525966fa6bbaade5f01',
    messagingSenderId: '1040296536084',
    projectId: 'clone-9b191',
    authDomain: 'clone-9b191.firebaseapp.com',
    storageBucket: 'clone-9b191.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAys0FNOlVW90kQiT8xt6Jr_0-il2BORrA',
    appId: '1:1040296536084:android:ab15c2770f61a917de5f01',
    messagingSenderId: '1040296536084',
    projectId: 'clone-9b191',
    storageBucket: 'clone-9b191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6yLCWXbMYn_HN3MpD9CTWa-1PAxHe-OA',
    appId: '1:1040296536084:ios:112452f3410daf18de5f01',
    messagingSenderId: '1040296536084',
    projectId: 'clone-9b191',
    storageBucket: 'clone-9b191.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6yLCWXbMYn_HN3MpD9CTWa-1PAxHe-OA',
    appId: '1:1040296536084:ios:112452f3410daf18de5f01',
    messagingSenderId: '1040296536084',
    projectId: 'clone-9b191',
    storageBucket: 'clone-9b191.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxIJRb3BkeZzRCUsTXegfm-2UdJo6QPdM',
    appId: '1:1040296536084:web:d9af5fdaf548a817de5f01',
    messagingSenderId: '1040296536084',
    projectId: 'clone-9b191',
    authDomain: 'clone-9b191.firebaseapp.com',
    storageBucket: 'clone-9b191.appspot.com',
  );
}
